services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  gateway:
    build: ./gateway
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=http://auth:3000
      - NOTIFICATION_SERVICE_URL=http://notification:5000
      - USER_SERVICE_URL=http://user:3000
      - TOUR_SERVICE_URL=http://tour:3000
      - BOOKING_SERVICE_URL=http://booking:3000
    depends_on:
      - auth
      - notification
      - user
      - tour
      - booking
    networks:
      - backend

  auth:
    build: ./services/auth
    command: node dist/server.js
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
    env_file:
      - ./services/auth/.env
    ports:
      - '3001:3000'
    networks:
      - backend
  user:
    build: ./services/user
    command: node dist/server.js
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
    env_file:
      - ./services/user/.env
    ports:
      - '3003:3000'
    networks:
      - backend
  tour:
    build: ./services/tour
    env_file:
      - ./services/tour/.env
    command: node dist/server.js
    environment:
      - NODE_ENV=development
    ports:
      - '3002:3000'
    networks:
      - backend
  booking:
    build: ./services/booking
    env_file:
      - ./services/booking/.env
    command: node dist/server.js
    environment:
      - NODE_ENV=development
    ports:
      - '3004:3000'
    networks:
      - backend

  notification:
    build: ./services/notification
    command: node dist/server.js
    env_file:
      - ./services/notification/.env
    ports:
      - '5001:5000'
    depends_on:
      - redis
    networks:
      - backend
  notification-worker:
    build: ./services/notification
    command: node dist/workers/emailWorker.js
    env_file:
      - ./services/notification/.env
    networks:
      - backend
    environment:
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025

    depends_on:
      - mailhog
      - redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # Cổng SMTP để service khác kết nối
      - '8025:8025' # Cổng Web UI để bạn xem email
    restart: unless-stopped
    networks:
      - backend
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mysql_data:
